# Data Analysis

In [4]:
'''
Group by -> grouping result in single set
Aggregate Functions -> mean, sum, max, min, count
'''

'\nGroup by -> grouping result in single set\nAggregate Functions -> mean, sum, max, min, count\n'

In [5]:
# Aggregate Functions -> mean (average), sum, max, min, count
# KPI (Key Performance Indicator)

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('D:/Broadway/Data Science - 2/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0

In [5]:
commission_mean = df['COMMISSION_PCT'].mean()
com_mean = "{:.2f}".format(commission_mean)

In [6]:
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(com_mean)

In [7]:
mgr_mode = df['MANAGER_ID'].mode()
mgr_mode

0    100.0
Name: MANAGER_ID, dtype: float64

In [8]:
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(mgr_mode)

In [9]:
dep_mode = df['DEPARTMENT_ID'].mode()
dep_mode

0    50.0
Name: DEPARTMENT_ID, dtype: float64

In [10]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(50.0)

In [11]:
df['DEPARTMENT_ID']

0       90.0
1       90.0
2       90.0
3       60.0
4       60.0
       ...
106    110.0
107     40.0
108     70.0
109    110.0
110    110.0
Name: DEPARTMENT_ID, Length: 111, dtype: float64

In [12]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [13]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0

In [14]:
# Find average, max, min, total salary of employees
mean_salary = df['SALARY'].mean()
print(mean_salary)

6560.576576576576

In [15]:
max_salary = df['SALARY'].max()
print(max_salary)

24000

In [16]:
min_salary = df['SALARY'].min()
print(min_salary)

2100

In [17]:
total_salary = df['SALARY'].sum()
print(total_salary)

728224

In [18]:
count_salary = df['SALARY'].count()
print(count_salary)

111

In [19]:
# Find total number of employees in each department.
# df.groupby(column_name)[column_name].count()
emp_dep = df.groupby('DEPARTMENT_ID')['EMPLOYEE_ID'].count().reset_index()
emp_dep

    DEPARTMENT_ID  EMPLOYEE_ID
0            10.0            1
1            20.0            2
2            30.0            6
3            40.0            2
4            50.0           46
5            60.0            5
6            70.0            2
7            80.0           34
8            90.0            3
9           100.0            6
10          110.0            4

In [20]:
# Find total number of employees according to Job
job_emp = df.groupby('JOB_ID')['EMPLOYEE_ID'].count().reset_index()
job_emp

        JOB_ID  EMPLOYEE_ID
0   AC_ACCOUNT            2
1       AC_MGR            2
2      AD_ASST            1
3      AD_PRES            1
4        AD_VP            2
5   FI_ACCOUNT            5
6       FI_MGR            1
7       HR_REP            2
8      IT_PROG            5
9       MK_MAN            1
10      MK_REP            1
11      PR_REP            2
12    PU_CLERK            5
13      PU_MAN            1
14      SA_MAN            5
15      SA_REP           30
16    SH_CLERK           20
17    ST_CLERK           20
18      ST_MAN            5

In [21]:
# Find total salary of employees according to Job.
job_sal = df.groupby('JOB_ID')['SALARY'].sum().reset_index()
job_sal

        JOB_ID  SALARY
0   AC_ACCOUNT   16600
1       AC_MGR   24016
2      AD_ASST    4400
3      AD_PRES   24000
4        AD_VP   34000
5   FI_ACCOUNT   39600
6       FI_MGR   12008
7       HR_REP   13000
8      IT_PROG   28800
9       MK_MAN   13000
10      MK_REP    6000
11      PR_REP   20000
12    PU_CLERK   13900
13      PU_MAN   11000
14      SA_MAN   61000
15      SA_REP  250500
16    SH_CLERK   64300
17    ST_CLERK   55700
18      ST_MAN   36400

In [22]:
# Find total number of Job available in each Departments.
dep_job = df.groupby('DEPARTMENT_ID')['JOB_ID'].count().reset_index()
dep_job

    DEPARTMENT_ID  JOB_ID
0            10.0       1
1            20.0       2
2            30.0       6
3            40.0       2
4            50.0      46
5            60.0       5
6            70.0       2
7            80.0      34
8            90.0       3
9           100.0       6
10          110.0       4

In [23]:
# Find average and total salary of employees by job
salary_details = df.groupby('JOB_ID').agg(
    average_salary = ('SALARY', 'mean'),
    total_salary = ('SALARY', 'sum'),
    max_salary = ('SALARY', 'max'),
    min_salary = ('SALARY', 'min')
).reset_index()
salary_details

        JOB_ID  average_salary  total_salary  max_salary  min_salary
0   AC_ACCOUNT          8300.0         16600        8300        8300
1       AC_MGR         12008.0         24016       12008       12008
2      AD_ASST          4400.0          4400        4400        4400
3      AD_PRES         24000.0         24000       24000       24000
4        AD_VP         17000.0         34000       17000       17000
5   FI_ACCOUNT          7920.0         39600        9000        6900
6       FI_MGR         12008.0         12008       12008       12008
7       HR_REP          6500.0         13000        6500        6500
8      IT_PROG          5760.0         28800        9000        4200
9       MK_MAN         13000.0         13000       13000       13000
10      MK_REP          6000.0          6000        6000        6000
11      PR_REP         10000.0         20000       10000       10000
12    PU_CLERK          2780.0         13900        3100        2500
13      PU_MAN         11000.0         11000       11000       11000
14      SA_MAN         12200.0         61000       14000       10500
15      SA_REP          8350.0        250500       11500        6100
16    SH_CLERK          3215.0         64300        4200        2500
17    ST_CLERK          2785.0         55700        3600        2100
18      ST_MAN          7280.0         36400        8200        5800

In [24]:
salary_details = df.groupby('JOB_ID')['SALARY'].agg(
    average_salary = ('mean'),
    total_salary = ('sum'),
    max_salary = ('max'),
    min_salary = ('min')
).reset_index()
salary_details

        JOB_ID  average_salary  total_salary  max_salary  min_salary
0   AC_ACCOUNT          8300.0         16600        8300        8300
1       AC_MGR         12008.0         24016       12008       12008
2      AD_ASST          4400.0          4400        4400        4400
3      AD_PRES         24000.0         24000       24000       24000
4        AD_VP         17000.0         34000       17000       17000
5   FI_ACCOUNT          7920.0         39600        9000        6900
6       FI_MGR         12008.0         12008       12008       12008
7       HR_REP          6500.0         13000        6500        6500
8      IT_PROG          5760.0         28800        9000        4200
9       MK_MAN         13000.0         13000       13000       13000
10      MK_REP          6000.0          6000        6000        6000
11      PR_REP         10000.0         20000       10000       10000
12    PU_CLERK          2780.0         13900        3100        2500
13      PU_MAN         11000.0         11000       11000       11000
14      SA_MAN         12200.0         61000       14000       10500
15      SA_REP          8350.0        250500       11500        6100
16    SH_CLERK          3215.0         64300        4200        2500
17    ST_CLERK          2785.0         55700        3600        2100
18      ST_MAN          7280.0         36400        8200        5800

In [3]:
# Average transaction per device
fraud = pd.read_csv('D:/Broadway/Data Science - 2/Cleaned_Fraud_Dataset.csv')

In [4]:
device_transaction = fraud.groupby('Device_Used')['Transaction_Amount'].mean().reset_index()
device_transaction

      Device_Used  Transaction_Amount
0         Desktop         2971.527100
1          Mobile         2999.391882
2          Tablet         2953.664185
3  Unknown Device         2950.144604

In [27]:
# Highest transaction per each transaction type
max_transaction = fraud.groupby('Transaction_Type')['Transaction_Amount'].max().reset_index()
max_transaction

  Transaction_Type  Transaction_Amount
0   ATM Withdrawal             49997.8
1    Bank Transfer             49997.8
2     Bill Payment             49997.8
3  Online Purchase             49997.8
4      POS Payment             49997.8

In [28]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  111 non-null    object
 9   MANAGER_ID      111 non-null    float64
 10  DEPARTMENT_ID   111 non-null    float64
dtypes: float64(2), int64(2), object(7)
memory usage: 9.7+ KB

In [30]:
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].astype(float)

In [31]:
# find total salary and average commision earned by each department
department_earned = df.groupby('DEPARTMENT_ID').agg(
    total_salary = ('SALARY', 'sum'),
    avg_commission = ('COMMISSION_PCT', 'mean')
).reset_index()
department_earned

    DEPARTMENT_ID  total_salary  avg_commission
0            10.0          4400        0.220000
1            20.0         19000        0.220000
2            30.0         24900        0.220000
3            40.0         13000        0.220000
4            50.0        163400        0.218478
5            60.0         28800        0.220000
6            70.0         20000        0.220000
7            80.0        304500        0.225000
8            90.0         58000        0.220000
9           100.0         51608        0.220000
10          110.0         40616        0.220000

In [32]:
# Find total salary of employees distributed by department and its job.
dep_job_sal = df.groupby(['JOB_ID', 'DEPARTMENT_ID'])['SALARY'].sum().reset_index()
dep_job_sal

        JOB_ID  DEPARTMENT_ID  SALARY
0   AC_ACCOUNT          110.0   16600
1       AC_MGR          110.0   24016
2      AD_ASST           10.0    4400
3      AD_PRES           90.0   24000
4        AD_VP           90.0   34000
5   FI_ACCOUNT          100.0   39600
6       FI_MGR          100.0   12008
7       HR_REP           40.0   13000
8      IT_PROG           60.0   28800
9       MK_MAN           20.0   13000
10      MK_REP           20.0    6000
11      PR_REP           70.0   20000
12    PU_CLERK           30.0   13900
13      PU_MAN           30.0   11000
14      SA_MAN           80.0   61000
15      SA_REP           50.0    7000
16      SA_REP           80.0  243500
17    SH_CLERK           50.0   64300
18    ST_CLERK           50.0   55700
19      ST_MAN           50.0   36400

In [33]:
'''
Find total salary and maximum salary, total commision of 
employees distributed by department and its job.
'''
# df.to_csv('')
sal_com_dep_job = df.groupby(['JOB_ID', 'DEPARTMENT_ID']).agg(
    total_sal = ('SALARY', 'sum'),
    max_sal = ('SALARY', 'max'),
    total_commission = ('COMMISSION_PCT', 'sum')
).reset_index()
sal_com_dep_job

        JOB_ID  DEPARTMENT_ID  total_sal  max_sal  total_commission
0   AC_ACCOUNT          110.0      16600     8300              0.44
1       AC_MGR          110.0      24016    12008              0.44
2      AD_ASST           10.0       4400     4400              0.22
3      AD_PRES           90.0      24000    24000              0.22
4        AD_VP           90.0      34000    17000              0.44
5   FI_ACCOUNT          100.0      39600     9000              1.10
6       FI_MGR          100.0      12008    12008              0.22
7       HR_REP           40.0      13000     6500              0.44
8      IT_PROG           60.0      28800     9000              1.10
9       MK_MAN           20.0      13000    13000              0.22
10      MK_REP           20.0       6000     6000              0.22
11      PR_REP           70.0      20000    10000              0.44
12    PU_CLERK           30.0      13900     3100              1.10
13      PU_MAN           30.0      11000    11000              0.22
14      SA_MAN           80.0      61000    14000              1.50
15      SA_REP           50.0       7000     7000              0.15
16      SA_REP           80.0     243500    11500              6.15
17    SH_CLERK           50.0      64300     4200              4.40
18    ST_CLERK           50.0      55700     3600              4.40
19      ST_MAN           50.0      36400     8200              1.10

In [34]:
'''
Find total salary of employees distributed by department and its job 
where salary must be more than 20000.
job id must be in AD_PRES/AD_VP/IT_PROG
'''
dep_job_sal = df.groupby(['JOB_ID', 'DEPARTMENT_ID'])['SALARY'].sum().reset_index()
filter_data = dep_job_sal['SALARY'] > 20000

In [35]:
dep_job_sal[filter_data]

        JOB_ID  DEPARTMENT_ID  SALARY
1       AC_MGR          110.0   24016
3      AD_PRES           90.0   24000
4        AD_VP           90.0   34000
5   FI_ACCOUNT          100.0   39600
8      IT_PROG           60.0   28800
14      SA_MAN           80.0   61000
16      SA_REP           80.0  243500
17    SH_CLERK           50.0   64300
18    ST_CLERK           50.0   55700
19      ST_MAN           50.0   36400

In [36]:
dep_job_sal = df.groupby(['JOB_ID', 'DEPARTMENT_ID'])['SALARY'].sum().reset_index()
filter_data = (dep_job_sal['SALARY'] > 20000) & (dep_job_sal['JOB_ID'].isin(['AD_PRES', 'AD_VP', 'IT_PROG']))
dep_job_sal[filter_data]

    JOB_ID  DEPARTMENT_ID  SALARY
3  AD_PRES           90.0   24000
4    AD_VP           90.0   34000
8  IT_PROG           60.0   28800

In [37]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0

In [38]:
# Extract year, month and day from hire_date
# column name must be hire_year, hire_month and hire_day
# Find total employees hired in each year.
# Find total employees hired in each month.
# Find total employees hired in each day.
# Find in which month maximum employees were hired.
# Find average number of employee hired according to month and its days.

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  111 non-null    float64
 9   MANAGER_ID      111 non-null    float64
 10  DEPARTMENT_ID   111 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [40]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])

In [41]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0

In [42]:
df['Hire_Year'] = df['HIRE_DATE'].dt.year
df['Hire_Month'] = df['HIRE_DATE'].dt.month_name()
df['Hire_Day'] = df['HIRE_DATE'].dt.day_name()

In [43]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Hire_Year,Hire_Month,Hire_Day
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0,2003,June,Tuesday
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0,2005,September,Wednesday
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0,2001,January,Saturday
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0,2006,January,Tuesday
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0,2007,May,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0,2002,June,Friday
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0,2002,June,Friday
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0,2002,June,Friday
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday

In [44]:
emp_hire_year = df.groupby('Hire_Year')['EMPLOYEE_ID'].count().reset_index()
emp_hire_year

   Hire_Year  EMPLOYEE_ID
0       2001            1
1       2002           11
2       2003            6
3       2004           10
4       2005           29
5       2006           24
6       2007           19
7       2008           11

In [45]:
emp_hire_month = df.groupby('Hire_Month')['EMPLOYEE_ID'].count().reset_index()
emp_hire_month

   Hire_Month  EMPLOYEE_ID
0       April            7
1      August            9
2    December            7
3    February           13
4     January           14
5        July            7
6        June           15
7       March           17
8         May            6
9    November            5
10    October            6
11  September            5

In [46]:
emp_hire_day = df.groupby('Hire_Day')['EMPLOYEE_ID'].count().reset_index()
emp_hire_day

    Hire_Day  EMPLOYEE_ID
0     Friday           23
1     Monday           10
2   Saturday           19
3     Sunday           15
4   Thursday           16
5    Tuesday           13
6  Wednesday           15

In [47]:
# Find average number of employee hired according to month and its days.

# month
# days

# Find in which month maximum employees were hired.
emp_hire_month = df.groupby('Hire_Month')['EMPLOYEE_ID'].count().reset_index()
filter_data = emp_hire_month['EMPLOYEE_ID'].max()

In [48]:
filter_data

17

In [49]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Hire_Year,Hire_Month,Hire_Day
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0,2003,June,Tuesday
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0,2005,September,Wednesday
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0,2001,January,Saturday
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0,2006,January,Tuesday
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0,2007,May,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0,2002,June,Friday
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0,2002,June,Friday
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0,2002,June,Friday
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday

In [50]:
# Categorical
weekday = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [51]:
df['Hire_Day'] = pd.Categorical(df['Hire_Day'], categories=weekday)

In [52]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,Hire_Year,Hire_Month,Hire_Day
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0,2003,June,Tuesday
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0,2005,September,Wednesday
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0,2001,January,Saturday
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0,2006,January,Tuesday
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0,2007,May,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0,2002,June,Friday
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0,2002,June,Friday
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0,2002,June,Friday
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0,2002,June,Friday

In [53]:
df['Hire_Day']

0        Tuesday
1      Wednesday
2       Saturday
3        Tuesday
4         Monday
         ...
106       Friday
107       Friday
108       Friday
109       Friday
110       Friday
Name: Hire_Day, Length: 111, dtype: category
Categories (7, object): ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [54]:
emp_hire_day = df.groupby('Hire_Day', observed=False)['EMPLOYEE_ID'].count().reset_index(name='Total_Employees')
emp_hire_day

    Hire_Day  Total_Employees
0     Sunday               15
1     Monday               10
2    Tuesday               13
3  Wednesday               15
4   Thursday               16
5     Friday               23
6   Saturday               19

In [55]:
emp_hire_day.rename(columns={'Hire_Day': 'Weekdays'})

    Weekdays  Total_Employees
0     Sunday               15
1     Monday               10
2    Tuesday               13
3  Wednesday               15
4   Thursday               16
5     Friday               23
6   Saturday               19

In [56]:
emp_hire_month = df.groupby('Hire_Month')['EMPLOYEE_ID'].count().sort_values(ascending=False).reset_index(name='Total_Employees')
emp_hire_month

   Hire_Month  Total_Employees
0       March               17
1        June               15
2     January               14
3    February               13
4      August                9
5       April                7
6    December                7
7        July                7
8         May                6
9     October                6
10   November                5
11  September                5

In [57]:
pz = pd.read_csv('pizza_sales.csv')
pz.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [58]:
# pz['Order_Hour'] = pz['order_time'].dt.hour

In [59]:
total_revenue = pz['total_price'].sum()
print(f"Total Revenue Collection: ${total_revenue:,.2f}")

Total Revenue Collection: $817,860.05

In [60]:
total_pizza_sold = pz['quantity'].sum()
print(f"Total Pizza Sold: {total_pizza_sold:,.2f}")

Total Pizza Sold: 49,574.00

In [61]:
average_order_value = total_revenue/total_pizza_sold
print(f"Average Order Value: ${average_order_value:,.2f}")

Average Order Value: $16.50

In [62]:
sales_by_category = pz.groupby('pizza_category')['total_price'].sum()
sales_by_category

pizza_category
Chicken    195919.50
Classic    220053.10
Supreme    208197.00
Veggie     193690.45
Name: total_price, dtype: float64

In [63]:
format_table = sales_by_category.map("Rs.{:,.2f}".format).to_markdown(numalign='left', stralign='left')

In [64]:
print(format_table)

| pizza_category   | total_price   |
|:-----------------|:--------------|
| Chicken          | Rs.195,919.50 |
| Classic          | Rs.220,053.10 |
| Supreme          | Rs.208,197.00 |
| Veggie           | Rs.193,690.45 |

# Student Dataset Analysis

In [65]:
st = pd.read_csv('student.csv')
st.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,very good,medium,high,very low,very low,good,6,5,6,6
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,excellent,medium,medium,very low,very low,good,4,5,5,6
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,very good,medium,low,low,medium,good,10,7,8,10
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,good,low,low,very low,very low,excellent,2,15,14,15
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,very good,medium,low,very low,low,excellent,4,6,10,10

In [66]:
st.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [67]:
st.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [68]:
st.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    object
 7   Fedu        395 non-null    object
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    object
 13  studytime   395 non-null    object
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    object
 24  freetime    395 non-null    object
 25  goout       395 non-null    object
 26  Dalc        395 non-null    object
 27  Walc        395 non-null    object
 28  health      395 non-null    object
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(6), object(27)
memory usage: 102.0+ KB

### Rename columns name using .rename() function

In [69]:
st.rename(columns={'G1': 'First_Test_Grade', 'G2': 'Second_Test_Grade', 'G3': 'Final_Grade'}, inplace=True)

In [70]:
st['health'].unique()

array(['good', 'excellent', 'very bad', 'bad', 'very good'], dtype=object)

# Label Encoding

In [71]:
health_data = {
    'very bad': 0,
    'bad': 1,
    'good': 2,
    'very good': 3,
    'excellent': 4
}

In [72]:
st['health_id'] = st['health'].map(health_data)

In [73]:
st

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,First_Test_Grade,Second_Test_Grade,Final_Grade,health_id
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,medium,high,very low,very low,good,6,5,6,6,2
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,medium,medium,very low,very low,good,4,5,5,6,2
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,medium,low,low,medium,good,10,7,8,10,2
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,low,low,very low,very low,excellent,2,15,14,15,4
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,medium,low,very low,low,excellent,4,6,10,10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,5th to 9th grade,5th to 9th grade,services,services,...,very high,high,high,very high,very good,11,9,9,9,3
391,MS,M,17,U,LE3,T,secondary education,primary education (4th grade),services,services,...,high,very high,medium,high,bad,3,14,16,16,1
392,MS,M,21,R,GT3,T,primary education (4th grade),primary education (4th grade),other,other,...,very high,medium,medium,medium,good,3,10,8,7,2
393,MS,M,18,R,LE3,T,secondary education,5th to 9th grade,services,other,...,high,very low,medium,high,excellent,0,11,12,10,4
394,MS,M,19,U,LE3,T,primary education (4th grade),primary education (4th grade),other,at_home,...,low,medium,medium,medium,excellent,5,8,9,9,4

### Enumerate function in for loop loops both index and value of a list

In [74]:
# for health_idx, health_value in enumerate(st['health']):
#     print(f"{health_idx}: {health_value}")

In [75]:
st.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,First_Test_Grade,Second_Test_Grade,Final_Grade,health_id
0,GP,F,18,U,GT3,A,higher education,higher education,at_home,teacher,...,medium,high,very low,very low,good,6,5,6,6,2
1,GP,F,17,U,GT3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,medium,medium,very low,very low,good,4,5,5,6,2
2,GP,F,15,U,LE3,T,primary education (4th grade),primary education (4th grade),at_home,other,...,medium,low,low,medium,good,10,7,8,10,2
3,GP,F,15,U,GT3,T,higher education,5th to 9th grade,health,services,...,low,low,very low,very low,excellent,2,15,14,15,4
4,GP,F,16,U,GT3,T,secondary education,secondary education,other,other,...,medium,low,very low,low,excellent,4,6,10,10,4

In [76]:
transaction = pd.read_csv('Fraud Detection Dataset.csv')
transaction.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [77]:
transaction.shape

(51000, 12)

In [78]:
# find duplicate records

In [79]:
transaction_duplicates = transaction.groupby('Transaction_ID')['Transaction_ID'].count().reset_index(name='count_transaction')
transaction_duplicates

find_duplicate = transaction_duplicates['count_transaction'] > 1
transaction_duplicates[find_duplicate]

transaction_id = input("Enter transaction id: ")
duplicate = transaction['Transaction_ID'] == transaction_id
transaction[duplicate]

transaction.drop_duplicates(subset='Transaction_ID', keep='first')

Enter transaction id:  1

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,T49996,1296,1844.08,Online Purchase,22.0,Desktop,Los Angeles,1,47,4,Credit Card,0
49996,T49997,3592,3274.95,POS Payment,15.0,Mobile,San Francisco,2,81,1,UPI,0
49997,T49998,3536,647.11,Bill Payment,11.0,Unknown Device,Miami,2,96,3,Debit Card,0
49998,T49999,2019,2446.65,POS Payment,9.0,Tablet,Boston,3,117,13,UPI,0
49999,T50000,3262,2867.43,Bank Transfer,14.0,Desktop,Miami,4,73,11,UPI,0

In [80]:
find_duplicate = transaction_duplicates['count_transaction'] > 1
transaction_duplicates[find_duplicate]

      Transaction_ID  count_transaction
47             T1004                  2
86            T10075                  2
87            T10076                  2
217           T10193                  2
347            T1031                  2
...              ...                ...
49930          T9936                  2
49948          T9952                  2
49954          T9958                  2
49958          T9961                  2
49989           T999                  2

[1000 rows x 2 columns]

In [81]:
transaction_id = input("Enter transaction id: ")
duplicate = transaction['Transaction_ID'] == transaction_id
transaction[duplicate]

Enter transaction id:  1001

Empty DataFrame
Columns: [Transaction_ID, User_ID, Transaction_Amount, Transaction_Type, Time_of_Transaction, Device_Used, Location, Previous_Fraudulent_Transactions, Account_Age, Number_of_Transactions_Last_24H, Payment_Method, Fraudulent]
Index: []

In [82]:
transaction.drop_duplicates(subset='Transaction_ID', keep='first')

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,T49996,1296,1844.08,Online Purchase,22.0,Desktop,Los Angeles,1,47,4,Credit Card,0
49996,T49997,3592,3274.95,POS Payment,15.0,Mobile,San Francisco,2,81,1,UPI,0
49997,T49998,3536,647.11,Bill Payment,11.0,Unknown Device,Miami,2,96,3,Debit Card,0
49998,T49999,2019,2446.65,POS Payment,9.0,Tablet,Boston,3,117,13,UPI,0
49999,T50000,3262,2867.43,Bank Transfer,14.0,Desktop,Miami,4,73,11,UPI,0

In [83]:
finance = pd.read_excel('financial_loan_data.xlsx')
finance.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [84]:
finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB

In [85]:
finance.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [141]:
finance['issue_date'] = pd.to_datetime(finance['issue_date'])

In [143]:
finance.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [144]:
finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB

In [227]:
finance[['annual_income', 'loan_amount']].describe()

       annual_income   loan_amount
count   3.857600e+04  38576.000000
mean    6.964454e+04  11296.066855
std     6.429368e+04   7460.746022
min     4.000000e+03    500.000000
25%     4.150000e+04   5500.000000
50%     6.000000e+04  10000.000000
75%     8.320050e+04  15000.000000
max     6.000000e+06  35000.000000

In [237]:
format_value = finance[['annual_income', 'loan_amount']].describe()

In [238]:
# finance['annual_income'].count()

In [244]:
print(format_value.map("{:,.2f}".format).to_markdown(numalign='left', stralign='left'))

|       | annual_income   | loan_amount   |
|:------|:----------------|:--------------|
| count | 38,576.00       | 38,576.00     |
| mean  | 69,644.54       | 11,296.07     |
| std   | 64,293.68       | 7,460.75      |
| min   | 4,000.00        | 500.00        |
| 25%   | 41,500.00       | 5,500.00      |
| 50%   | 60,000.00       | 10,000.00     |
| 75%   | 83,200.50       | 15,000.00     |
| max   | 6,000,000.00    | 35,000.00     |