In [1]:
import pandas as pd

In [39]:
df = pd.read_csv('Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0

# Drop Null value

In [42]:
df.shape

(111, 11)

In [44]:
df.size

1221

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [48]:
# default row wise delete (axis=0, how='any'), inplace=True/False
# df.dropna(inplace=True)

In [50]:
# df.shape

In [9]:
# Drop null values columns (axis=1, how='any')
# df.dropna(axis=1, inplace=True)

In [10]:
# df.dropna(axis=0, how='any', inplace=True)

# Fill Null values

## Filling custom records for null values

In [13]:
df = pd.read_csv('Employees.csv')

In [14]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [15]:
# df.fillna(0, inplace=True)

In [16]:
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(0)

In [17]:
# df['MANAGER_ID'] = df['MANAGER_ID'].fillna(0)
# df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(0)

In [18]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0

In [19]:
commission = df['COMMISSION_PCT'] > 0
df[commission]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,145,John,Russell,JRUSSEL,011.44.1344.429268,2004-10-01,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,2005-01-05,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,2005-03-10,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,2007-10-15,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,2008-01-29,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,2005-01-30,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,2005-03-24,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,2005-08-20,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,2006-03-30,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,2006-12-09,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,2007-11-23,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,2004-01-30,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,2004-03-04,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,2004-08-01,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,2005-03-10,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,2005-12-15,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,2006-11-03,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,2005-11-11,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,2007-03-19,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,2008-01-24,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2008-02-23,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,2008-03-24,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,2008-04-21,SA_REP,6200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,2005-03-11,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,2006-03-23,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,2006-01-24,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2007-02-23,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,2007-03-24,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,2008-04-21,SA_REP,6100,0.10,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,2004-05-11,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,2005-03-19,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,2006-03-24,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,2006-04-23,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,2007-05-24,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2008-01-04,SA_REP,6200,0.10,149.0,80.0

In [20]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [21]:
# Aggregate Functions
# ---------------------------
# mean
# max
# min
# count
# sum

In [22]:
commission_mean = df['COMMISSION_PCT'].mean()
com_mean = "{:.2f}".format(commission_mean)
com_mean
# com_mean = f"{commission_mean:.2f}"

'0.22'

In [23]:
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(com_mean)

In [24]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0

In [88]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         0
DEPARTMENT_ID      0
dtype: int64

In [65]:
mgr_mode = df['MANAGER_ID'].mode()
mgr_mode

0    100.0
Name: MANAGER_ID, dtype: float64

In [86]:
df['MANAGER_ID'] = df['MANAGER_ID'].fillna(mgr_mode)

In [63]:
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0

In [75]:
dep_mode = df['DEPARTMENT_ID'].mode()
dep_mode

0    50.0
Name: DEPARTMENT_ID, dtype: float64

In [81]:
df['DEPARTMENT_ID'] = df['DEPARTMENT_ID'].fillna(dep_mode)[0]

In [83]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         0
DEPARTMENT_ID      0
dtype: int64

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    datetime64[ns]
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      111 non-null    float64
 10  DEPARTMENT_ID   111 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 9.7+ KB

In [94]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'])

In [98]:
pz = pd.read_csv('pizza_sales.csv')
pz

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,31/12/2015,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,31/12/2015,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,31/12/2015,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,31/12/2015,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,31/12/2015,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [116]:
'''
1. '%m.%d.%y'
2. '%m/%d/%y'
3. mixed
4. dayfirst=True
'''
pz['order_date'] = pd.to_datetime(pz['order_date'], dayfirst=True)

In [114]:
pz

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,2015-12-31,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,2015-12-31,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,2015-12-31,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,2015-12-31,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza