In [1]:
import pandas as pd

In [2]:
hr = pd.read_csv('HR_Dataset Refresh.csv')
# Top 5
hr.head()
# Bottom 5
hr.tail()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [3]:
# Regular Expression (Regex)
# ,./+-&^%$@!$%^&()[]{}
# Replace(find, value_replace, regex=False)

# White Space
# '     Production Department     '
# Strip()

In [4]:
hr['Employee_Name'] = hr['Employee_Name'].str.replace(',',' ',regex=False)

In [5]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [6]:
prod_dep = hr['Department'] == 'Production'
hr[prod_dep]

Empty DataFrame
Columns: [Employee_Name, EmpID, MarriedID, MaritalStatusID, GenderID, EmpStatusID, DeptID, PerfScoreID, FromDiversityJobFairID, Salary, Termd, PositionID, Position, State, Zip, DOB, Gender, MaritalDesc, CitizenDesc, HispanicLatino, RaceDesc, DateofHire, DateofTermination, TermReason, EmploymentStatus, Department, ManagerName, ManagerID, RecruitmentSource, PerformanceScore, EngagementSurvey, EmpSatisfaction, SpecialProjectsCount, LastPerformanceReview_Date, DaysLateLast30, Absences]
Index: []

[0 rows x 36 columns]

In [7]:
# Remove White Space
hr['Department'] = hr['Department'].str.strip()

In [8]:
hr['Department']

0                Production
1                     IT/IS
2                Production
3                Production
4                Production
               ...
577              Production
578              Production
579    Software Engineering
580              Production
581              Production
Name: Department, Length: 582, dtype: object

In [9]:
hr['DateofHire']

0        7/5/2011
1       3/30/2015
2        7/5/2011
3        1/7/2008
4       7/11/2011
          ...
577     7/11/2011
578      1/9/2012
579    11/10/2014
580     9/30/2013
581      7/6/2009
Name: DateofHire, Length: 582, dtype: object

In [10]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

In [11]:
hr['DateofHire'] = pd.to_datetime(hr['DateofHire'])

In [19]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    datetime64[ns]
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  First_Name                  582 non-null    object
 37  Middle_Name                 582 non-null    object
 38  Last_Name                   550 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(16), object(20)
memory usage: 177.5+ KB

# Extract first name, middle name and last name of employees

In [12]:
# split(find, num_of_column=index, expand=True)
# Employee_Name
hr[['First_Name', 'Middle_Name', 'Last_Name']] = hr['Employee_Name'].str.split(' ',n=2, expand=True)

In [13]:
# first_name  = pd.Series(['A', 'B'])

In [14]:
hr_data = {
    'first_name': ['a', 'b'],
    'middle_name': ['c', 'd'],
    'last_name': ['e', 'f']
}

In [15]:
names = pd.DataFrame(hr_data)

In [16]:
names

  first_name middle_name last_name
0          a           c         e
1          b           d         f

In [17]:
hr['Employee_Name']

0           Adinolfi  Wilson  K
1      Ait Sidi  Karthikeyan
2             Akinkuolie  Sarah
3                  Alagbe Trina
4              Anderson  Carol
                 ...
577            Anderson  Carol
578           Anderson  Linda
579             Andreola  Colby
580                 Athwal  Sam
581            Bachiochi  Linda
Name: Employee_Name, Length: 582, dtype: object

In [18]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,First_Name,Middle_Name,Last_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Adinolfi,,Wilson K
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Akinkuolie,,Sarah
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,Alagbe,Trina,None
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,,Carol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Anderson,,Carol
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Anderson,,Linda
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Andreola,,Colby
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Athwal,,Sam
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Bachiochi,,Linda

# Extract Year, Month and Day

In [20]:
hr['Hire_Year'] = hr['DateofHire'].dt.year

In [22]:
hr['Hire_Month'] = hr['DateofHire'].dt.month
hr['Hire_Day'] = hr['DateofHire'].dt.day

In [24]:
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,First_Name,Middle_Name,Last_Name,Hire_Year,Hire_Month,Hire_Day
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,0,1/17/2019,0,1,Adinolfi,,Wilson K,2011,7,5
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,6,2/24/2016,0,17,Ait,Sidi,Karthikeyan,2015,3,30
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,0,5/15/2012,0,3,Akinkuolie,,Sarah,2011,7,5
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,0,1/3/2019,0,15,Alagbe,Trina,None,2008,1,7
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2/1/2016,0,2,Anderson,,Carol,2011,7,11

In [25]:
hr['Month_Name'] = hr['DateofHire'].dt.month_name()
hr['Day_Name'] = hr['DateofHire'].dt.day_name()

In [26]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,DaysLateLast30,Absences,First_Name,Middle_Name,Last_Name,Hire_Year,Hire_Month,Hire_Day,Month_Name,Day_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,0,1,Adinolfi,,Wilson K,2011,7,5,July,Tuesday
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,0,17,Ait,Sidi,Karthikeyan,2015,3,30,March,Monday
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,0,3,Akinkuolie,,Sarah,2011,7,5,July,Tuesday
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,0,15,Alagbe,Trina,None,2008,1,7,January,Monday
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2,Anderson,,Carol,2011,7,11,July,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2,Anderson,,Carol,2011,7,11,July,Monday
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,0,15,Anderson,,Linda,2012,1,9,January,Monday
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,0,19,Andreola,,Colby,2014,11,10,November,Monday
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,0,19,Athwal,,Sam,2013,9,30,September,Monday
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,0,4,Bachiochi,,Linda,2009,7,6,July,Monday

In [58]:
fraud = pd.read_csv('Fraud Detection Dataset.csv')
fraud.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [47]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  object
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                48480 non-null  float64
 3   Transaction_Type                  51000 non-null  object
 4   Time_of_Transaction               48448 non-null  float64
 5   Device_Used                       48527 non-null  object
 6   Location                          48453 non-null  object
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    48531 non-null  object
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.7+ MB

In [48]:
fraud['Transaction_Type'].unique()

array(['ATM Withdrawal', 'Bill Payment', 'POS Payment', 'Bank Transfer',
       'Online Purchase'], dtype=object)

In [49]:
fraud['Device_Used'].unique()

array(['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device'], dtype=object)

In [50]:
fraud['Transaction_Type'].nunique()

5

In [51]:
fraud['Transaction_ID'].nunique()

50000

In [52]:
# fraud['Time_of_Transaction'].astype(int)

In [74]:
fraud.isnull().sum()

Transaction_ID                      0
User_ID                             0
Transaction_Amount                  0
Transaction_Type                    0
Time_of_Transaction                 0
Device_Used                         0
Location                            0
Previous_Fraudulent_Transactions    0
Account_Age                         0
Number_of_Transactions_Last_24H     0
Payment_Method                      0
Fraudulent                          0
dtype: int64

In [54]:
device_mode = fraud['Device_Used'].mode()
device_mode

0    Desktop
Name: Device_Used, dtype: object

In [61]:
fraud['Device_Used'] = fraud['Device_Used'].fillna('Unknown Device')

In [62]:
fraud['Device_Used'].unique()

array(['Tablet', 'Mobile', 'Desktop', 'Unknown Device'], dtype=object)

In [57]:
fraud['Time_of_Transaction'].unique()

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [64]:
fraud['Location'].unique()

array(['San Francisco', 'New York', 'No Location', 'Chicago', 'Boston',
       'Houston', 'Miami', 'Los Angeles', 'Seattle'], dtype=object)

In [63]:
fraud['Location'] = fraud['Location'].fillna('No Location')

In [67]:
mean_amount = fraud['Transaction_Amount'].median()

In [68]:
fraud['Transaction_Amount'] = fraud['Transaction_Amount'].fillna(mean_amount)

In [71]:
fraud['Time_of_Transaction'] = fraud['Time_of_Transaction'].fillna(0)

In [73]:
fraud['Payment_Method'] = fraud['Payment_Method'].fillna('Unknown Method')

In [81]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transaction_ID                    51000 non-null  object
 1   User_ID                           51000 non-null  int64
 2   Transaction_Amount                51000 non-null  float64
 3   Transaction_Type                  51000 non-null  object
 4   Time_of_Transaction               51000 non-null  int64
 5   Device_Used                       51000 non-null  object
 6   Location                          51000 non-null  object
 7   Previous_Fraudulent_Transactions  51000 non-null  int64
 8   Account_Age                       51000 non-null  int64
 9   Number_of_Transactions_Last_24H   51000 non-null  int64
 10  Payment_Method                    51000 non-null  object
 11  Fraudulent                        51000 non-null  int64
dtypes: float64(1), int64(6), object(5)
memory usage: 4.7+ MB

In [80]:
fraud['Time_of_Transaction'] = fraud['Time_of_Transaction'].astype(int)

In [82]:
fraud['Transaction_ID'].drop_duplicates()

0            T1
1            T2
2            T3
3            T4
4            T5
          ...
49995    T49996
49996    T49997
49997    T49998
49998    T49999
49999    T50000
Name: Transaction_ID, Length: 50000, dtype: object

In [85]:
fraud.to_csv('Cleaned_Fraud_Dataset.csv', index=False)

In [84]:
fraud

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,0,Mobile,No Location,3,115,9,Unknown Method,0
3,T4,2294,100.10,Bill Payment,15,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3,Tablet,Los Angeles,0,50,10,Invalid Method,0