In [1]:
'''
Pandas used for data analysis, data cleaning, data mainpulation, data read and write
'''

'\nPandas used for data analysis, data cleaning, data mainpulation, data read and write\n'

In [2]:
# 1D -> Series and 2D -> DataFrame

In [3]:
import pandas as pd

In [4]:
series = pd.Series([1, 2, 3])
series

0    1
1    2
2    3
dtype: int64

In [5]:
df = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6]
], columns=['num1', 'num2', 'num3'], index=['A', 'B'])
df

   num1  num2  num3
A     1     2     3
B     4     5     6

In [6]:
series = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
series

A    1
B    2
C    3
dtype: int64

In [7]:
data = {
    'Name': ['Charles', 'Bob', 'John'],
    'Age': [20, 30, 40],
    'City': ['Kathmandu', 'Bhaktapur', 'Lalitpur'],
    'Phone': [123, 456, 789]
}

In [8]:
details = pd.DataFrame(data, index=['A', 'B', 'C'])

In [9]:
details

      Name  Age       City  Phone
A  Charles   20  Kathmandu    123
B      Bob   30  Bhaktapur    456
C     John   40   Lalitpur    789

In [10]:
details['A':'C']

      Name  Age       City  Phone
A  Charles   20  Kathmandu    123
B      Bob   30  Bhaktapur    456
C     John   40   Lalitpur    789

In [11]:
# loc -> location
# iloc -> integer location

In [12]:
details.loc['A':'B', 'Age':'City']

   Age       City
A   20  Kathmandu
B   30  Bhaktapur

In [13]:
details.iloc[0:2, 1:3]

   Age       City
A   20  Kathmandu
B   30  Bhaktapur

In [14]:
details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
 3   Phone   3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [15]:
details.shape

(3, 4)

In [16]:
details.size

12

# Conditional Filtering

In [18]:
# CSV (Comma Separated Values)
# Excel File

# Excel File

In [20]:
employee = pd.read_excel('EMPLOYEES.xlsx')

In [21]:
employee

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,07.06.2002 00:00:00,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0

In [22]:
csvdata = pd.read_csv('Employees.csv')
csvdata

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [23]:
# displays first 5 records
employee.head(10)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,17.08.2002 00:00:00,FI_MGR,12008,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,16.08.2002 00:00:00,FI_ACCOUNT,9000,NaN,108.0,100.0

In [24]:
# displays botton 5 records
employee.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,07.06.2002 00:00:00,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0

In [25]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [26]:
# NaN (Not a Number)
employee.isnull().sum().sum()

78

In [27]:
# Find record of employees who works on department 60 and 90.
emp_dep = (employee['DEPARTMENT_ID'] == 60) | (employee['DEPARTMENT_ID'] == 90)
employee[emp_dep]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0

In [28]:
# find details of employees whose salary is less than 24000, more than 7000
emp_sal = (employee['SALARY'] >= 7000) & (employee['SALARY'] <= 24000)
employee[emp_sal]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,17.08.2002 00:00:00,FI_MGR,12008,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,16.08.2002 00:00:00,FI_ACCOUNT,9000,NaN,108.0,100.0
10,110,John,Chen,JCHEN,515.124.4269,28.09.2005 00:00:00,FI_ACCOUNT,8200,NaN,108.0,100.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30.09.2005 00:00:00,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07.03.2006 00:00:00,FI_ACCOUNT,7800,NaN,108.0,100.0
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,07.12.2002 00:00:00,PU_MAN,11000,NaN,100.0,30.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,18.07.2004 00:00:00,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,10.04.2005 00:00:00,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01.05.2003 00:00:00,ST_MAN,7900,NaN,100.0,50.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,01.10.2004 00:00:00,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,05.01.2005 00:00:00,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,10.03.2005 00:00:00,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,15.10.2007 00:00:00,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,29.01.2008 00:00:00,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,30.01.2005 00:00:00,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,24.03.2005 00:00:00,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,20.08.2005 00:00:00,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,30.03.2006 00:00:00,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,09.12.2006 00:00:00,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,23.11.2007 00:00:00,SA_REP,7000,0.15,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,30.01.2004 00:00:00,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,04.03.2004 00:00:00,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,01.08.2004 00:00:00,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,10.03.2005 00:00:00,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,15.12.2005 00:00:00,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,03.11.2006 00:00:00,SA_REP,7000,0.25,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11.11.2005 00:00:00,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,19.03.2007 00:00:00,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,24.01.2008 00:00:00,SA_REP,7200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,11.03.2005 00:00:00,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,23.03.2006 00:00:00,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,24.01.2006 00:00:00,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,23.02.2007 00:00:00,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,24.03.2007 00:00:00,SA_REP,7300,0.15,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,11.05.2004 00:00:00,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,19.03.2005 00:00:00,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,24.03.2006 00:00:00,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,23.04.2006 00:00:00,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,24.05.2007 00:00:00,SA_REP,7000,0.15,149.0,NaN
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,17.02.2004 00:00:00,MK_MAN,13000,NaN,100.0,20.0
104,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0

In [29]:
# Find employee details who works under job AD_VP, AD_PRES, IT_PROG, AC_MGR, AC_ACCOUNT
emp_job = (employee['JOB_ID'] == 'AD_VP') | (employee['JOB_ID'] == 'AD_PRES') | (employee['JOB_ID'] == 'IT_PROG') | (employee['JOB_ID'] == 'AC_MGR') | (employee['JOB_ID'] == 'AC_ACCOUNT')
employee[emp_job]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0

In [75]:
# between
# (employee['SALARY'] >= 7000) & (employee['SALARY'] <= 24000)
salary_between = employee['SALARY'].between(7000, 24000)
employee[salary_between]

# isin

# (employee['JOB_ID'] == 'AD_VP') | (employee['JOB_ID'] == 'AD_PRES') | (employee['JOB_ID'] == 'IT_PROG') | (employee['JOB_ID'] == 'AC_MGR') | (employee['JOB_ID'] == 'AC_ACCOUNT')
job_isin = employee['JOB_ID'].isin(['AD_VP', 'AD_PRES', 'IT_PROG', 'AC_MGR'])
employee[job_isin]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0

In [67]:
# and
# salary >= 7000 and salary <= 240000

# between(7000, 24000)

In [73]:
# (employee['JOB_ID'] == 'AD_VP') | (employee['JOB_ID'] == 'AD_PRES') | (employee['JOB_ID'] == 'IT_PROG') | (employee['JOB_ID'] == 'AC_MGR') | (employee['JOB_ID'] == 'AC_ACCOUNT')
job_isin = employee['JOB_ID'].isin(['AD_VP', 'AD_PRES', 'IT_PROG', 'AC_MGR'])
employee[job_isin]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,25.06.2005 00:00:00,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,05.02.2006 00:00:00,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,07.02.2007 00:00:00,IT_PROG,4200,NaN,103.0,60.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0

In [78]:
df = pd.read_csv('HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [112]:
# 1. Find details of employees with the salary range of 50000 to 70000 and who are Married.
emp_detail = ((df['Salary'] >= 50000) & (df['Salary'] <= 70000)) & (df['MaritalDesc'] == 'Married')
df[emp_detail]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
10,"Baczenski, Rachael",10252,1,1,0,5,5,3,1,54670,...,David Stanley,14.0,Diversity Job Fair,Fully Meets,4.20,4,0,1/30/2016,0,12
21,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
22,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
566,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
567,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
575,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
576,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15

In [118]:
# 2. Details of employees who works under production department and their employment status is active as well.
dep_emp = (df['Department'] == 'Production       ') & (df['EmploymentStatus'] == 'Active')
df.loc[dep_emp, ['Department', 'EmploymentStatus']]

            Department EmploymentStatus
0    Production                  Active
3    Production                  Active
5    Production                  Active
7    Production                  Active
8    Production                  Active
..                 ...              ...
573  Production                  Active
576  Production                  Active
578  Production                  Active
580  Production                  Active
581  Production                  Active

[274 rows x 2 columns]

In [120]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [124]:
# 3. Details of employees who works under IT/IS department and their absences record must be more than 8.
emp_abs = (df['Department'] == 'IT/IS') & (df['Absences'] > 8)
df.loc[emp_abs, ['Department', 'Absences']]

    Department  Absences
1        IT/IS        17
9        IT/IS        16
12       IT/IS         9
20       IT/IS        17
28       IT/IS        16
31       IT/IS         9
80       IT/IS        19
89       IT/IS        15
94       IT/IS        16
115      IT/IS        15
127      IT/IS        10
128      IT/IS        20
132      IT/IS        11
189      IT/IS        14
209      IT/IS        13
216      IT/IS        17
232      IT/IS        19
239      IT/IS        16
247      IT/IS        10
257      IT/IS        15
258      IT/IS        12
259      IT/IS        17
262      IT/IS        13
273      IT/IS        16
280      IT/IS        19
281      IT/IS        13
294      IT/IS        14
303      IT/IS        11
311      IT/IS         9
317      IT/IS        17
327      IT/IS        16
328      IT/IS        11
331      IT/IS        17
340      IT/IS        17
349      IT/IS        17
358      IT/IS        17
367      IT/IS        17
376      IT/IS        17
385      IT/IS        17
394      IT/IS        17
403      IT/IS        17
412      IT/IS        17
421      IT/IS        17
430      IT/IS        17
439      IT/IS        17
448      IT/IS        17
457      IT/IS        17
466      IT/IS        17
475      IT/IS        17
484      IT/IS        17
493      IT/IS        17
502      IT/IS        17
511      IT/IS        17
520      IT/IS        17
529      IT/IS        17
538      IT/IS        17
547      IT/IS        17
556      IT/IS        17
565      IT/IS        17
574      IT/IS        17

In [126]:
# ETL -> Extract, Transform (Cleaning, Feature Engineering, Label Encoding), Load
# Data Wrangling

# ELT -> Extract, Load, Transform

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB